spring.application.name=clinivo_backend

# Database connection
spring.datasource.url=jdbc:postgresql://localhost:5432/clinivo
spring.datasource.username=postgres
spring.datasource.password=sesame

# JDBC Driver
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Show SQL (dev only)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Cloud Port Binding
server.port=${PORT:8080}